CREATE TABLE SETTINGS (
  SETTINGKEY VARCHAR(255) NOT NULL,
  SETTINGVALUE VARCHAR(255) NOT NULL,
  PRIMARY KEY (SETTINGKEY)
);

CREATE TABLE MOCKEDFIELDS (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  CONTEXTPATH VARCHAR(255) NOT NULL,
  CLASSNAME VARCHAR(255) NOT NULL,
  FIELDNAME VARCHAR(255) NOT NULL,
  FIELDTYPE VARCHAR(255) NOT NULL DEFAULT 'java.lang.String',
  FIELDVALUE VARCHAR(32000),
  PRIMARY KEY (ID),
  UNIQUE (CONTEXTPATH, CLASSNAME, FIELDNAME)
);