CREATE TABLE SETTINGS (
  SETTINGKEY VARCHAR(255) NOT NULL,
  SETTINGVALUE VARCHAR(255) NOT NULL,
  PRIMARY KEY (SETTINGKEY)
);

CREATE TABLE MOCKEDFIELDS (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  CONTEXTPATH VARCHAR(255) NOT NULL,
  CLASSNAME VARCHAR(1024) NOT NULL,
  FIELDNAME VARCHAR(255) NOT NULL,
  FIELDTYPE VARCHAR(1024) NOT NULL DEFAULT 'java.lang.String',
  FIELDVALUE VARCHAR(32000),
  EXPRESSION VARCHAR(32000),
  FIELDELEMENTTYPE VARCHAR(1024),
  ACTIVE SMALLINT NOT NULL DEFAULT 0,
  PRIMARY KEY (ID),
  UNIQUE (CONTEXTPATH, CLASSNAME, FIELDNAME)
);

CREATE TABLE WEBAPPLICATIONDESCRIPTOR (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  CONTEXTPATH VARCHAR(255) NOT NULL,
  INSTALLATIONPATH VARCHAR(32000) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (CONTEXTPATH, INSTALLATIONPATH)  
);

CREATE TABLE WEBAPPLICATIONDESCRIPTORELEMENT (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  CONTEXTPATH VARCHAR(255) NOT NULL,
  PATH VARCHAR(32000) NOT NULL,
  KIND VARCHAR(255), /*COULD BE "CLASSPATH" OR "BLACKLISTED"*/
  PRIMARY KEY(ID)
);

CREATE TABLE JNDI_DATASOURCE (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  RESOURCENAME VARCHAR(255) NOT NULL,
  RESOURCETYPE VARCHAR(255) NOT NULL DEFAULT 'javax.sql.DataSource',
  DRIVERCLASSNAME VARCHAR(255) DEFAULT 'com.mysql.jdbc.Driver',
  CONNECTIONURL VARCHAR(32000) DEFAULT 'jdbc:mysql://',
  DRIVERJAR VARCHAR(32000), /* JAR FILE NAME $HOME/.ejisto/lib/JAR-FILE-NAME */
  USERNAME VARCHAR(32000) ,
  PASSWORD VARCHAR(32000) ,
  MAXACTIVE INT NOT NULL DEFAULT 5,
  MAXWAIT INT NOT NULL DEFAULT 100,
  MAXIDLE INT NOT NULL DEFAULT 2,
  PRIMARY KEY (ID),
  UNIQUE(RESOURCENAME)
);

CREATE TABLE CUSTOMOBJECTFACTORY (
  FILENAME VARCHAR(255) NOT NULL,
  CHECKSUM VARCHAR(1024) NOT NULL,
  PROCESSED SMALLINT NOT NULL DEFAULT 1,
  PRIMARY KEY(FILENAME)
);

CREATE TABLE CONTAINER (
  ID VARCHAR(255) NOT NULL,
  CARGOID VARCHAR(255) NOT NULL,
  HOMEDIR VARCHAR(32000) NOT NULL,
  DESCRIPTION VARCHAR(32000),
  PRIMARY KEY (ID)
);