/*
 * Ejisto, a powerful developer assistant
 *
 * Copyright (C) 2010  Celestino Bellone
 *
 * Ejisto is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Ejisto is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.ejisto.modules.gui.components.helper;

import com.ejisto.modules.dao.entities.MockedField;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import org.jdesktop.swingx.JXLabel;

import javax.swing.*;
import java.awt.*;
import java.util.List;
import java.util.Vector;


/**
 * Created by IntelliJ IDEA.
 * User: celestino
 * Date: 12/19/10
 * Time: 1:47 PM
 */
public class MockedFieldValueEditorPanel {
    private JXLabel title;
    private JXLabel type;
    private JComboBox genericType;
    private JButton ok;
    private JButton cancel;
    private List<String> types;
    private MockedField mockedField;
    private JPanel editor;

    public MockedFieldValueEditorPanel(MockedField mockedField, List<String> types) {
        this.types = types;
        this.mockedField = mockedField;
        $$$setupUI$$$();
    }

    public JPanel getEditor() {
        return editor;
    }

    public String getValueAsString() {
        return "";
    }

    private void createUIComponents() {
        editor = new JPanel();
        title = new JXLabel("title");
        type = new JXLabel("type");
        genericType = new JComboBox(new Vector<String>(types));
        ok = new JButton("ok");
        cancel = new JButton("cancel");
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        editor.setLayout(new FormLayout("fill:max(d;4px):grow,left:4dlu:noGrow,fill:max(p;60px):grow,left:4dlu:noGrow,fill:216px:noGrow,left:9px:grow,fill:max(d;4px):noGrow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        editor.setBackground(new Color(-1));
        title.setText("title");
        CellConstraints cc = new CellConstraints();
        editor.add(title, cc.xyw(3, 1, 3));
        editor.add(type, cc.xy(3, 3));
        editor.add(genericType, cc.xy(5, 3));
        editor.add(ok, cc.xy(3, 5));
        editor.add(cancel, cc.xy(5, 5));
        type.setLabelFor(genericType);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return editor;
    }
}
